services:
  - type: web
    name: laravel-docker-demo
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: /start.sh
    region: singapore
    plan: free
    branch: main
    envVars:
      - fromGroup: laravel-demo
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-laravel-demo
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis-laravel-demo
          type: redis
          property: connectionString
  - type: redis
    name: redis-laravel-demo
    region: singapore
    plan: free
    ipAllowList: [] # only allow internal connections

databases:
  - name: postgresql-laravel-demo
    region: singapore
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
