services:
  # production
  - type: web
    name: laravel-demo-prd
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: /start.sh
    region: singapore
    plan: Starter
    branch: main
    envVars:
      - fromGroup: laravel-demo-secrets-common
      - fromGroup: laravel-demo-secrets-prd
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-laravel-demo-prd
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis-laravel-demo-prd
          type: redis
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
    autoDeploy: false

  # staging
  - type: web
    name: laravel-demo-stg
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: /start.sh
    region: singapore
    plan: Free
    branch: develop
    envVars:
      - fromGroup: laravel-demo-secrets-common
      - fromGroup: laravel-demo-secrets-stg
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-laravel-demo-stg
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis-laravel-demo-stg
          type: redis
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: TEST
        sync: false
    autoDeploy: false

  - type: redis
    name: redis-laravel-demo-prd
    region: singapore
    plan: Starter
    ipAllowList: [] # only allow internal connections

  - type: redis
    name: redis-laravel-demo-stg
    region: singapore
    plan: Free
    ipAllowList: [] # only allow internal connections

databases:
  - name: postgresql-laravel-demo-prd
    region: singapore
    plan: Starter
    ipAllowList: [] # only allow internal connections
  - name: postgresql-laravel-demo-stg
    region: singapore
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

envVarGroups:
  - name: laravel-demo-secrets-common
    envVars:
      - key: DEFAULT_TIMEZONE
        sync: false
      - key: DEFAULT_LANG
        sync: false

  - name: laravel-demo-secrets-prd
    envVars:
      - key: APP_NAME
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: SESSION_COOKIE
        sync: false
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PLAN
        sync: false
      - key: STRIPE_PLAN_NAME
        sync: false
      - key: FCM_SECRET_KEY
        sync: false
      - key: ENTRANCE_CURRENCY
        sync: false

  - name: laravel-demo-secrets-stg
    envVars:
      - key: APP_NAME
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: SESSION_COOKIE
        sync: false
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PLAN
        sync: false
      - key: STRIPE_PLAN_NAME
        sync: false
      - key: FCM_SECRET_KEY
        sync: false
      - key: ENTRANCE_CURRENCY
        sync: false
